[package]
name = "wifidaemon_daemon"
version = "0.1.0"
edition = "2021"
authors = ["Chinedu <github.com/umenyi-bryan>"]

[dependencies]
pcap = "0.11"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
